[project]
name = "agentic-ai-learning"
version = "0.1.0"
description = "A practical learning laboratory for agentic AI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.optional-dependencies]
openai = ["openai>=2", "socksio>=1,<2"]
gemini = ["google-genai>=1", "socksio>=1,<2"]
groq = [
    "groq>=0.30",
    "langchain-groq>=1.1.3",
    "socksio>=1,<2",
    "langchain>=0.3.0"
]
openrouter = ["openai>=2", "socksio>=1,<2"]

[tool.uv]
package = false
